[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.aito.app https://*.aito.ai"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy to avoid CORS issues
[[proxies]]
  from = "/api/*"
  to = "https://aito-grocery-store.aito.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Forms handling (if needed)
[[forms]]
  name = "contact"

# Plugin configuration
[[plugins]]
  package = "netlify-plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-sitemap"

# Environment-specific settings
[context.production.environment]
  REACT_APP_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  REACT_APP_ENVIRONMENT = "staging"

[context.branch-deploy.environment]
  REACT_APP_ENVIRONMENT = "development"